#Fileupload config
uploadPath: /opt/payara/deployments/resources

#Database connection config
path: jdbc:mysql://dam2.mysql.iesquevedo.es:3335/QuevedoClassrooms?useSSL=false
user: root
password: quevedo2dam
driver: com.mysql.cj.jdbc.Driver
